### ISSUE TITLE
repomon报错了

### ISSUE THREAD

**Issue by petronny** [lilydjwg/archrepo2#4]
```
[E 08-10 12:55:04.955 ioloop:801] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fc904b89510>)
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
        ret = callback()
      File "/usr/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/calil/.local/lib/python3.7/site-packages/archrepo2-0.6.dev0-py3.7.egg/archrepo2/repomon.py", line 217, in run
        self._do_add(toadd)
      File "/home/calil/.local/lib/python3.7/site-packages/archrepo2-0.6.dev0-py3.7.egg/archrepo2/repomon.py", line 124, in _do_add
        self._do_cmd(self._command_add, files, callbacks)
      File "/home/calil/.local/lib/python3.7/site-packages/archrepo2-0.6.dev0-py3.7.egg/archrepo2/repomon.py", line 116, in _do_cmd
        self.queue_command(cmd1, callbacks)
      File "/home/calil/.local/lib/python3.7/site-packages/archrepo2-0.6.dev0-py3.7.egg/archrepo2/repomon.py", line 81, in queue_command
        self.run_command()
      File "/home/calil/.local/lib/python3.7/site-packages/archrepo2-0.6.dev0-py3.7.egg/archrepo2/repomon.py", line 96, in run_command
        p = tornado.process.Subprocess(cmd, io_loop=self._ioloop)
      File "/usr/lib/python3.7/site-packages/tornado/process.py", line 240, in __init__
        self.proc = subprocess.Popen(*args, **kwargs)
    TypeError: __init__() got an unexpected keyword argument 'io_loop'
```

**Comment by lilydjwg** [comment]
应该修好了。这么快五年就过去了呢。
